default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: osumosan_development
  
test:
  <<: *default
  database: osumosan_test


production:
  <<: *default
  database: osumosan_production
  username: osumosan
  password: <%= ENV['OSUMOSAN_DATABASE_PASSWORD'] %>
